"""Provider-parity tests: the schema must apply cleanly on managed Postgres.

Supabase restricts a handful of Postgres extensions and privileges. Our schema
only relies on core PG constructs (IDENTITY, JSONB, boolean/text server
defaults), which are fully supported on managed Postgres. These tests pin that
contract so a migration introducing an unsupported extension fails loudly.
"""

from pathlib import Path

from sqlalchemy.schema import CreateTable

from app.models import Base

MIGRATIONS_DIR = Path(__file__).parent.parent / "alembic" / "versions"

FORBIDDEN_EXTENSIONS = (
    "CREATE EXTENSION",
    "CREATE EXTENSION IF NOT EXISTS",
)

REQUIRED_CONSTRUCTS = {
    "doc_updates": {"diff_payload_placeholder": "is_trivial", "token_usage": True},
}


def _all_migrations() -> list[str]:
    return [p.read_text() for p in sorted(MIGRATIONS_DIR.glob("*.py"))]


def test_no_extension_ddl_in_migrations() -> None:
    for text in _all_migrations():
        for ext in FORBIDDEN_EXTENSIONS:
            assert ext not in text, f"migration references unsupported DDL: {ext}"


def test_all_tables_render_as_core_postgres_ddl() -> None:
    rendered = [
        str(CreateTable(table).compile(dialect=None)) for table in Base.metadata.sorted_tables
    ]
    joined = "\n".join(rendered)
    assert "CREATE TABLE" in joined
    assert "JSONB" in joined or "JSON" in joined
    assert "GENERATED BY DEFAULT AS IDENTITY" in joined or "SERIAL" in joined


def test_core_tenancy_tables_present() -> None:
    table_names = {t.name for t in Base.metadata.sorted_tables}
    required = {
        "organizations",
        "users",
        "org_memberships",
        "sources",
        "snapshots",
        "diffs",
        "docs",
        "doc_updates",
        "run_logs",
        "org_llm_usage",
        "refresh_tokens",
    }
    assert required.issubset(table_names)