"""Docs ID

Revision ID: dda4699585d1
Revises: 0004
Create Date: 2026-08-09 18:43:34.350268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda4699585d1'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docs_org_id_updated_at'), table_name='docs')
    op.drop_constraint(op.f('fk_docs_source_id_sources'), 'docs', type_='foreignkey')
    op.drop_index(op.f('ix_snapshots_source_id_fetched_at'), table_name='snapshots')
    op.create_index('ix_snapshots_source_id_fetched_at', 'snapshots', ['source_id', 'fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshots_source_id_fetched_at', table_name='snapshots')
    op.create_index(op.f('ix_snapshots_source_id_fetched_at'), 'snapshots', ['source_id', sa.literal_column('fetched_at DESC')], unique=False)
    op.create_foreign_key(op.f('fk_docs_source_id_sources'), 'docs', 'sources', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_docs_org_id_updated_at'), 'docs', ['org_id', sa.literal_column('updated_at DESC')], unique=False)
    # ### end Alembic commands ###
